version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.google.android.material:material
    versions:
    - 1.3.0
    - 1.3.0-rc01
    - 1.4.0-alpha01
  - dependency-name: com.android.tools.build:gradle
    versions:
    - 4.1.2
  - dependency-name: org.codehaus.groovy:groovy-all
    versions:
    - 3.0.7
